#!/bin/bash
app=ofbiz

# Retrieve arguments
domain=$1
path=$2
admin=$3
is_public=$4

# Save app settings
yunohost app setting $app admin -v "$admin"
yunohost app setting $app is_public -v "$is_public"
apt-get install openjdk-7-jdk -y
apt-get install postgre -y

# Check domain/path availability
yunohost app checkurl $domain$path -a ofbiz
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Copy source files
final_path=/var/www/$app
app_path=/opt/ofbiz
uri_path=/catalog/control/main
mkdir -p $final_path
mkdir -p $app_path
cp -a ../sources/* $app_path
cp $app_path/tools/rc.ofbiz.for.debian /etc/init.d/ofbiz
chmod +x /etc/init.d/ofbiz
update-rc.d ofbiz defaults 90

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS:8444@$uri_path/@g" ../conf/nginx.conf
cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# If app is public, add url to SSOWat conf as skipped_uris
if [ "$is_public" != "No" ];
then
  yunohost app setting $app skipped_uris -v "/"
fi

# Restart services
service nginx reload
yunohost app ssowatconf
ofbiz start
