#!/bin/bash
app=ofbiz

# Retrieve arguments
domain=$(yunohost app setting $app domain)
path=$(yunohost app setting $app path)
admin=$(yunohost app setting $app admin)
is_public=$(yunohost app setting $app is_public)

# Remove sources
sudo rm -rf /var/www/$app
sudo rm -rf /opt/ofbiz
sudo rm -rf /etc/init.d/ofbiz

# Remove configuration files
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf

sudo sed '/^ofbiz/ d' /root/.bashrc

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf
