#!/bin/bash
app=ofbiz

# Retrieve arguments
domain=$(yunohost app setting $app domain)
path=$(yunohost app setting $app path)
admin=$(yunohost app setting $app admin)
is_public=$(yunohost app setting $app is_public)

# Remove sources
rm -rf /var/www/$app
rm -rf /opt/ofbiz

# Remove configuration files
rm -f /etc/nginx/conf.d/$domain.d/$app.conf

# Restart services
service nginx reload
yunohost app ssowatconf
